name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      # Key fix: Install dependencies with rebuild
      - name: Install dependencies
        run: npm ci --ignore-scripts && npm rebuild

      - name: Build project
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OREL_PORTFOLIO_WEBSITE }}"
          channelId: live
          projectId: orel-portfolio-website
